### ISSUE TITLE
Can't read machine GUID

### ISSUE THREAD

**Issue by andruhon** [gentoo90/winreg-rs#10]
Example with reading Program Files dir works well, however this one does not:
```Rust
    let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
    let win_crypt = hklm.open_subkey_with_flags("SOFTWARE\\Microsoft\\Cryptography",
        KEY_READ).unwrap();
    let guid: String = win_crypt.get_value("MachineGuid").unwrap();
    println!("guid: {}",guid);
```

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Process didn't exit successfully: `target\debug\request-generator.exe` (exit code: 101)

**Comment by gentoo90** [comment]
Works for me. Have you checked in `regedit.exe` if this key exists? Can you specify platform, OS version and rust version?

**Comment by andruhon** [comment]
The key exist.

Platform: Windows 10 Pro
rustc 1.8.0-nightly

**Comment by gentoo90** [comment]
Can't check on win 10 right now. There is already stable release of `1.8.0` and `1.9.0`. Can you try some of those? May be a bug of this particular nightly.

**Comment by andruhon** [comment]
Ah! My OS is 64bit, however I use 32bit compiler (because I 32bit build). 
x86_64-pc-windows-msvc-stable (rust 1.9) - works well,
i686-pc-windows-msvc-stable - does not

Probably that's a reason.

**Comment by gentoo90** [comment]
Yes, for 32-bit software 64-bit OS will substitute `HKLM\SOFTWARE\` path with `HKLM\SOFTWARE\Wow6432Node\`. So you were trying to read `HKLM\SOFTWARE\Wow6432Node\Microsoft\Cryptography\MachineGuid` which doesn't exist.

**Comment by gentoo90** [comment]
If you need to access 64-bit registry from 32-bit app, you can
```rust
hklm.open_subkey_with_flags("SOFTWARE\\Microsoft\\Cryptography",
        KEY_READ|KEY_WOW64_64KEY)
```

**Comment by andruhon** [comment]
Cool, thanks! It works now.

Is there a way to detect that we have the 32bit app running in 64bit OS? I think that conditional compilation is not what I need here. What I currently do is re-trying 64 bit flag if 32bit approach failed and if this one failed as well finally returning Err

**Comment by gentoo90** [comment]
[`IsWow64Process`](https://stackoverflow.com/questions/7011071/detect-32-bit-or-64-bit-of-windows). It's in `kernel32` crate
