### ISSUE TITLE
REG_MULTI_SZ parsing shouldn't replace nulls with newlines; use a Vec instead!

### ISSUE THREAD

**Issue by ErichDonGubler** [gentoo90/winreg-rs#16]
I don't understand the reason for one of the implementation details noted in the [FromRegValue](https://gentoo90.github.io/winreg-rs/v0.5.0/winreg/types/trait.FromRegValue.html) trait:

> **NOTE:** When converting to `String`, trailing `NULL` characters are trimmed and line separating `NULL` characters in `REG_MULTI_SZ` are replaced by `\n`. When converting to `OsString`, all `NULL` characters are left as is.

[Windows docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724884(v=vs.85).aspx) state that `REG_MULTI_SZ` represents a "sequence of null-terminated strings, terminated by an empty string", which communicates to me that a `REG_MULTI_SZ` is better modeled by a `Vec<String>`; in other words, the intermediary nulls represent the end of an individual string element, instead of the line separator of a single that the docs seem to indicate. Furthermore, using a newline character seems like a potentially problematic behavior if a stored `REG_MULTI_SZ` already contains newlines:

```rust
extern crate encoding;

use encoding::all::UTF_16LE;

fn parse_reg_multi_sz(s: String) -> Vec<String> {
    s.into_iter().split('\n').collect() // Presumably correct splitting behavior according to docs
}

fn main() {
    // The UTF-16 bytes of the problematic string gets stored as:
    // "just\0some\0strings\nyo\0\0"
    let registry_data: String  = { // Coerced to a single `String`, per documented behavior in `FromRegValue`.
        let hive = RegKey::predef(/* ... */);
        let key = hive.open_subkey(/* ... */);
        key.get_value(&"something").unwrap()
    };

    assert_eq!(parse_reg_multi_sz(registry_data), vec!["just", "some", "strings\nyo"); // panics because this was parsed as ["just", "some", "strings", "yo"]
}
```

I'm more than happy to submit a PR with some design and implementation work to fix this issue, if it is accepted as a defect. :)

**Comment by gentoo90** [comment]
>the intermediary nulls represent the end of an individual string element, instead of the line separator of a single that the docs seem to indicate

I didn't think of that. When I wrote this code, I was testing `MULTI_SZ` with `regedit.exe` and it replaces `\n`s with `\0`s when saving the value from the editor window so I was thinking of it as of a multiline string.
I rechecked now and indeed API allows to save `\n`s as is.
I've added `impl FromRegValue for Vec<String>` and `impl<T: AsRef<OsStr>> ToRegValue for Vec<T>` in 34bba99 ([multi_sz](/gentoo90/winreg-rs/tree/multi_sz) branch).

Please let me know if that's what you need.

**Comment by jorgenpt** [comment]
@gentoo90, I was just about to fork winreg to create a pull request for this! Any chance this'll get integrated to main? I'd love to use this in my project, otherwise I have to implement my own set of escaping & delimiters to do this, or use separate keys. :)

**Comment by gentoo90** [comment]
@jorgenpt, I didn't merge this because later I tried to add impls for `Vec<u8>` and found out that it causes a conflict:
![изображение](https://user-images.githubusercontent.com/1297574/118361319-96d08500-b593-11eb-9f73-3a0cbf00d478.png)
So I decided to wait until rust-lang/rust#31844 lands.

But giving it a second thought I suppose `impl<T: AsRef<OsStr>> ToRegValue for Vec<T>` can be replaced with `impl<'a> ToRegValue for Vec<&'a str>`.
