### ISSUE TITLE
Convert String to HKEY

### ISSUE THREAD

**Issue by cyberpunkbln** [gentoo90/winreg-rs#24]
Hello,

can anybody say me how i can a String convert to an HKEY. I want to deliver a String trough an function but don't want to import the HKEY Modul in the caller function.

registry::get_value ("HKEY_LOCAL_MACHINE".to_string(),"".to_string(),"".to_string());

thx

**Comment by gentoo90** [comment]
Getting root keys by string name is not supported. That would break type safety.

**Comment by porterbmoody** [comment]
std::string hex_key = match[2].str();
            ULONG_PTR key_num;
            std::stringstream ss;
            ss << std::hex << hex_key;
            ss >> key_num;
            HKEY hkey = (HKEY)key_num;


i used the regex pattern "(#define\s+(HKEY_[A-Z_]+)\s+\(\(HKEY\)\s+\(ULONG_PTR\)\(\(LONG\)(0x[0-9A-Fa-f]+)\)\))"

to get the filename and hex number matches 
then used the hex number to create the HKEY
