### ISSUE TITLE
OsString::from_reg_value shouldn't preserve null terminator

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [gentoo90/winreg-rs#34]
Example code:

```rust
use std::ffi::OsString;
use std::os::windows::ffi::OsStringExt;
use std::path::PathBuf;

use winreg::enums::HKEY_CURRENT_USER;
use winreg::RegKey;

fn main() {
    let base = RegKey::predef(HKEY_CURRENT_USER);
    let desktop = base.open_subkey(r#"Control Panel\Desktop"#).unwrap();
    // read using OsString
    let wallpaper: OsString = desktop.get_value("WallPaper").unwrap();
    let path = PathBuf::from(wallpaper);
    println!("Wallpaper exists? {}, path is {:?}", path.exists(), path);
    // read using String
    let wallpaper: String = desktop.get_value("WallPaper").unwrap();
    let path = PathBuf::from(wallpaper);
    println!("Wallpaper exists? {}, path is {:?}", path.exists(), path);
    // read manually
    let wallpaper = desktop.get_raw_value("WallPaper").unwrap();
    let mut raw: Vec<u16> = wallpaper
        .bytes
        .chunks_exact(2)
        .into_iter()
        .map(|c| u16::from_le_bytes([c[0], c[1]]))
        .collect();
    while raw.ends_with(&[0]) {
        raw.pop();
    }
    let path = PathBuf::from(OsString::from_wide(&raw));
    println!("Wallpaper exists? {}, path is {:?}", path.exists(), path);
}

```

On my machine this prints:

```
Wallpaper exists? false, path is "C:\\Users\\X\\AppData\\Local\\Packages\\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\\LocalState\\Assets\\0659d89079d32d12eab382d73089f7997f00ee80d8d6c053dc879e956600804b\u{0}"
Wallpaper exists? true, path is "C:\\Users\\X\\AppData\\Local\\Packages\\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\\LocalState\\Assets\\0659d89079d32d12eab382d73089f7997f00ee80d8d6c053dc879e956600804b"
Wallpaper exists? true, path is "C:\\Users\\X\\AppData\\Local\\Packages\\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\\LocalState\\Assets\\0659d89079d32d12eab382d73089f7997f00ee80d8d6c053dc879e956600804b"
```

(these may all print false on your machine as internally it caches elsewhere; I just needed a simpler repro)

The null terminator on the OsString causes the PathBuf to have a path to a non-existent file. As a result, I have to choose between using a String (lossy if Unicode is ill-formed) or manually turning the registry's bytes into an OsString (lossless but complex, not sure my method is 100% correct).

From [the OsString docs](https://doc.rust-lang.org/std/ffi/struct.OsString.html): 

>OsString and OsStr bridge this gap by simultaneously representing Rust and platform-native string values, and in particular allowing a Rust string to be converted into an "OS" string with no cost if possible. **A consequence of this is that OsString instances are not NUL terminated**; in order to pass to e.g., Unix system call, you should create a CStr.

**Comment by gentoo90** [comment]
I specifically intended `OsString` to be NUL terminated and be a replacement for `CString`, which cannot be used with WinAPI functions because they use UTF-16. [`widestring`](https://crates.io/crates/widestring/) crate could probably be used for that but that's an additional dependency. And I also haven't found any clean way to get rid of NULs in `OsString`. Seems like they're not intended to be editable.

> using a String (lossy if Unicode is ill-formed)

Do you have any specific example of that?
