### ISSUE TITLE
example for mock key to test gets?

### ISSUE THREAD

**Issue by tinsel-grumble** [gentoo90/winreg-rs#44]
is possible to add example on a way for mock a key to test functions? ex i make a key to replicate a key with vals. i want to test function return expected data. not sure how to test other than live which may need admin depend on key lookup not sure how to point a function to made up key vs real

**Comment by gentoo90** [comment]
I'm not aware of any straightforward way of mocking windows registry. If you want to test a function which does something to a registry key, then you you best bet is passing this key to it as an argument:
```rust
fn do_stuff_with_registry_key(key: &RegKey) {
    // ...
}
```
and then in the tests you can just pass a fake key to it.

**Comment by tinsel-grumble** [comment]
thx
