### ISSUE TITLE
Is there any way to set the default value?

### ISSUE THREAD

**Issue by fuyoo** [gentoo90/winreg-rs#46]
Is there any way to set the default value?

**Comment by gentoo90** [comment]
`name` should be an empty string:
```rust
key.set_value("", &"Test123")?;
let default: String = key.get_value("")?;
```
![изображение](https://user-images.githubusercontent.com/1297574/143769348-daf811ea-a838-4b0a-aab0-94840a4fc80b.png)

**Comment by fuyoo** [comment]
thank you!
