### ISSUE TITLE
Check if value exists

### ISSUE THREAD

**Issue by smacdo** [gentoo90/winreg-rs#53]
Looking through the crate's documentation I don't see any way to check if a key in a subkey exists, eg:

```rust
        let key = winreg::RegKey::predef(winreg::enums::HKEY_CURRENT_USER)
            .open_subkey(FOO_REGISTRY_PATH)?;

        // this returns an error...
        key.get_value("a key that does not exist");

        // so I'd like to test first
        if key.contains_value("a key that does not exist") {
           // ....
        }
```

Other ways I could think to do this would make `get_value` return an Option although this would break back compat. Maybe `try_get_value` which returns `Option`? Or just stick with a new method that only checks for existence?

**Comment by gentoo90** [comment]
It does return an error and the error has a kind:
```rust
hkcu.open_subkey(&path).unwrap_or_else(|e| match e.kind() {
    io::ErrorKind::NotFound => panic!("Key doesn't exist"),
    io::ErrorKind::PermissionDenied => panic!("Access denied"),
    _ => panic!("{:?}", e),
});
```

And if you don't care about the error kind, you can just:
```rust
if let Ok(subkey) = hkcu.open_subkey(&path) {
    // do stuff
}
```

**Comment by smacdo** [comment]
You are right - I have no idea how I missed the Result when I was looking through the docs! I swear I'm not crazy, but in this case I'm glad to be wrong.
