### ISSUE TITLE
[ Feature ] RegKey Export: Maybe via RegSaveKey | RegSaveKeyEx 

### ISSUE THREAD

**Issue by dfirence** [gentoo90/winreg-rs#57]
Can you extend this awesome lib to have a new lib method to export the registry key to `.reg` format?

Unless I missed it in the docs, I only saw the `copy_tree()` method available, but I would like to have capabilities to export a key.

**Comment by gentoo90** [comment]
[`RegSaveKey`](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regsavekeyw)/[`RegSaveKeyEx`](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regsavekeyexw) don't create `*.reg` files. They create binary [registry files](https://learn.microsoft.com/en-us/windows/win32/sysinfo/registry-files) that can be connected and used by applications. There is no API for exporting/importing `*.reg` files as far as I'm aware.

I guess you could use `serde` to create your own, using JSON as an example:
https://github.com/gentoo90/winreg-rs/blob/1c56127adf4e310b5c8ed2af89aa3f7b09d38371/examples/reg2json.rs#L12-L20

But I'd rather just call [`reg.exe export`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg-export)/[`reg.exe import`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg-import) that are guaranteed to work.

**Comment by dfirence** [comment]
That makes sense @gentoo90 - Thanks for looking into it, and applying the change to the `rename` request.
