### ISSUE TITLE
[ Feature ] RegKeyRename

### ISSUE THREAD

**Issue by dfirence** [gentoo90/winreg-rs#58]
Can you extend the lib to offer rename of RegKey objects?

maybe `https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regrenamekey`

**Comment by gentoo90** [comment]
Fixed in [`0.13.0`](https://crates.io/crates/winreg/0.13.0)(winapi)/[`0.52.0`](https://crates.io/crates/winreg/0.52.0)(windows-rs)

**Comment by dfirence** [comment]
Wonderful @gentoo90 - Thank you for the feature
