### ISSUE TITLE
Unable to refer to or use `EncodeError`

### ISSUE THREAD

**Issue by FrancisRussell** [gentoo90/winreg-rs#59]
`EncodeError` is a public type, however it is defined in the `encoder` module which is not public. It appear to be impossible for me to write code that uses this type, because there is no way to reference it.

**Comment by gentoo90** [comment]
Fixed in [`0.13.0`](https://crates.io/crates/winreg/0.13.0)(winapi)/[`0.52.0`](https://crates.io/crates/winreg/0.52.0)(windows-rs)
