### ISSUE TITLE
Make `commit` and `rollback` consume the transaction

### ISSUE THREAD

**Issue by omer54463** [gentoo90/winreg-rs#62]
As far as I can tell, `commit` and `rollback` should consume the transaction.
Is there any reason this hasn't been done that I'm missing?
I guess it COULD be problematic if the function fails, but what are you going to do if `CommitTransaction` fails except log it, anyways?

**Comment by gentoo90** [comment]
Fixed in [`0.13.0`](https://crates.io/crates/winreg/0.13.0)(winapi)/[`0.52.0`](https://crates.io/crates/winreg/0.52.0)(windows-rs)
